version: "3.11"
services:
  modelo:
    build: ./modelo
    volumes:
      - ./resultados:/app/modelo/resultados
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./resultados:/app/api/resultados
    depends_on:
      - modelo
    env_file:
      - .env  # Apunta al archivo .env
  app:
    build: ./app
    ports:
      - "8501:8501"
    depends_on:
      - api